### ISSUE TITLE
Error: Socket closed abruptly during opening handshake

### ISSUE THREAD

**Issue by roshanlabh** [hnasr/javascript_playground#6]
Hi,

I am getting this below error:

`λ node publisher.js
OperationalError: Socket closed abruptly during opening handshake
    at Socket.endWhileOpening (D:\misc\htdocs\git-public-repos\javascript_playground\rabbitmq\node_modules\amqplib\lib\connection.js:260:17)
    at Socket.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  cause: Error: Socket closed abruptly during opening handshake
      at Socket.endWhileOpening (D:\misc\htdocs\git-public-repos\javascript_playground\rabbitmq\node_modules\amqplib\lib\connection.js:260:17)
      at Socket.emit (events.js:322:22)
      at endReadableNT (_stream_readable.js:1187:12)
      at processTicksAndRejections (internal/process/task_queues.js:84:21),
  isOperational: true
}
`
FYI, my rabbitmq is successfully running on http://localhost:15672/

**Comment by hnasr** [comment]
it was a bug at my end , forgot to add "await" when sending messages

should be ok , pull the latest rabbitMQ code
